import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function CoverLetterPage({ searchParams }: { searchParams: Promise<{ id?: string }> }) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return <main className="min-h-screen bg-[#f7f8fc] text-[#090d1f]">
      <header className="border-b border-slate-200/70 bg-white"><div className="mx-auto flex max-w-[1200px] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3 font-black"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#090d1f] text-sm text-white">JC</span><span className="text-xl">Job<span className="text-violet-600">Craft</span></span></Link><div className="flex items-center gap-2"><Link href="/cover-letter?auth=login" scroll={false} className="hidden px-4 py-2.5 text-sm font-bold sm:block">Log in</Link><Link href="/cover-letter?auth=signup" scroll={false} className="rounded-xl bg-[#090d1f] px-5 py-3 text-sm font-bold text-white">Get started</Link></div></div></header>
      <section className="mx-auto grid max-w-[1200px] gap-8 px-5 py-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-20"><div><p className="text-xs font-black tracking-[.15em] text-violet-600">COVER LETTER WORKSPACE</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">Create role-specific letters without inventing your story.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">JobCraft keeps cover letters tied to the role, your real skills and the career information you supplied.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/cover-letter?auth=signup" scroll={false} className="rounded-xl bg-violet-600 px-6 py-3.5 font-black text-white">Create your workspace →</Link><Link href="/jobs" className="rounded-xl border border-slate-200 bg-white px-6 py-3.5 font-black">Explore jobs</Link></div></div><div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_20px_60px_rgba(15,23,42,.08)]"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.14em] text-violet-600">DRAFT PREVIEW</p><h2 className="mt-2 text-2xl font-black">Data Analyst application</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">Grounded draft</span></div><div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm leading-7 text-slate-600">Dear Hiring Manager,<br/><br/>I am applying for the Data Analyst role. My experience with SQL, Power BI and Excel aligns with the core requirements listed for the position...</div><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Role-specific","Truthful","Reusable"].map(x=><div key={x} className="rounded-xl border border-slate-200 p-3 text-center text-sm font-black">{x}</div>)}</div></div></section>
    </main>;
  }

  const { data: letters } = await supabase.from("cover_letters").select("id,title,body,created_at,updated_at").eq("user_id", user.id).order("updated_at", { ascending: false });
  const selected = params.id ? letters?.find((letter) => letter.id === params.id) : letters?.[0];

  return <main className="min-h-screen bg-[#f7f8fc] text-[#090d1f]"><div className="mx-auto max-w-[1280px] px-5 py-9 sm:px-8">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Link href="/dashboard" className="text-sm font-black text-violet-600">← Dashboard</Link><p className="mt-5 text-xs font-black tracking-[.15em] text-violet-600">COVER LETTER WORKSPACE</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Keep every application letter grounded and specific.</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">Current drafts use a rules-based template tied to job and profile information. AI rewriting comes later, but it will still stay grounded in facts you supplied.</p></div><Link href="/jobs" className="rounded-xl bg-violet-600 px-6 py-3.5 font-bold text-white">Choose a job →</Link></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><aside><div className="rounded-[22px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Your drafts</h2><span className="text-xs font-black text-slate-400">{letters?.length ?? 0}</span></div><div className="mt-4 space-y-2">{letters?.length ? letters.map((letter) => <Link key={letter.id} href={`/cover-letter?id=${letter.id}`} className={`block rounded-xl border p-4 transition ${selected?.id===letter.id?"border-violet-200 bg-violet-50":"border-slate-200 bg-white hover:border-violet-200"}`}><p className="font-black">{letter.title}</p><p className="mt-1 text-xs text-slate-500">Updated {new Date(letter.updated_at ?? letter.created_at).toLocaleDateString()}</p></Link>) : <div className="rounded-xl border border-dashed border-slate-300 p-5 text-sm leading-6 text-slate-500">No letters yet. Open a job and create one from the application tools.</div>}</div></div><div className="mt-4 rounded-[22px] border border-violet-100 bg-violet-50 p-5"><p className="text-sm font-black text-violet-950">A good JobCraft letter should</p><ul className="mt-3 space-y-2 text-sm leading-6 text-violet-900"><li>• mention the target role clearly</li><li>• connect only real skills and experience</li><li>• avoid invented achievements</li><li>• stay concise and role-specific</li></ul></div></aside>
    <section className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-[0_16px_45px_rgba(15,23,42,.05)] sm:p-8">{selected ? <><div className="flex flex-col justify-between gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-start"><div><p className="text-xs font-black tracking-[.14em] text-violet-600">SELECTED DRAFT</p><h2 className="mt-2 text-2xl font-black">{selected.title}</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">Truthful template</span></div><div className="mt-6 whitespace-pre-wrap rounded-2xl border border-slate-200 bg-slate-50 p-6 leading-8 text-slate-700">{selected.body}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/jobs" className="rounded-xl bg-[#090d1f] px-5 py-3 text-center font-bold text-white">Create for another job</Link><Link href="/applications" className="rounded-xl border border-slate-200 px-5 py-3 text-center font-bold">Open application tracker</Link></div><p className="mt-5 text-xs leading-5 text-slate-400">Later AI can improve tone and specificity, but JobCraft should never add qualifications, projects, achievements or experience that are not supported by the user profile or resume.</p></> : <div className="py-16 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-50 text-2xl">✉</div><h2 className="mt-5 text-2xl font-black">Create your first cover letter</h2><p className="mx-auto mt-2 max-w-md leading-7 text-slate-500">Choose a job and use its application tools to create a role-specific draft.</p><Link href="/jobs" className="mt-6 inline-block rounded-xl bg-violet-600 px-6 py-3.5 font-bold text-white">Browse jobs →</Link></div>}</section></div>
  </div></main>;
}
