import Link from "next/link";

const features = [
  ["01", "Discover", "Search India-first roles with practical filters for salary, skills, experience and work mode.", "⌕"],
  ["02", "Understand your fit", "See the signals behind your JobCraft match before deciding where to spend your time.", "◎"],
  ["03", "Build & tailor", "Keep ATS-friendly resumes and role-specific versions together in one workspace.", "▤"],
  ["04", "Track progress", "Move applications from saved to applied, interview and offer without losing context.", "↗"],
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f8f8fc] text-[#090d1f]">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-[1380px] items-center justify-between px-5 py-4 sm:px-8">
      <Link href="/" className="flex items-center gap-3 font-black tracking-tight"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#090d1f] text-sm text-white shadow-lg">JC</span><span className="text-xl">Job<span className="text-violet-600">Craft</span></span></Link>
      <nav className="hidden items-center gap-8 text-sm font-semibold text-slate-500 lg:flex"><Link href="/jobs" className="hover:text-slate-950">Jobs</Link><Link href="/resume" className="hover:text-slate-950">Resume</Link><Link href="/applications" className="hover:text-slate-950">Applications</Link><Link href="/career-assistant" className="hover:text-slate-950">Career Assistant</Link></nav>
      <div className="flex items-center gap-2"><Link href="/auth/login" className="hidden px-4 py-2 text-sm font-bold sm:block">Log in</Link><Link href="/auth/signup" className="rounded-xl bg-[#090d1f] px-5 py-3 text-sm font-bold text-white shadow-lg transition hover:-translate-y-0.5">Get started free</Link></div>
    </div></header>

    <section className="relative bg-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_25%,rgba(124,58,237,.12),transparent_28%),radial-gradient(circle_at_82%_25%,rgba(14,165,233,.09),transparent_27%)]"/><div className="relative mx-auto grid max-w-[1380px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:py-24">
      <div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-violet-100 bg-violet-50/80 px-4 py-2 text-sm font-bold text-violet-700"><span className="h-2 w-2 rounded-full bg-violet-500"/>Career workspace built for India</div>
        <h1 className="mt-7 text-[3.35rem] font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-[5.25rem]">Find the right role.<br/><span className="bg-gradient-to-r from-violet-600 via-indigo-500 to-violet-500 bg-clip-text text-transparent">Know why it fits.</span></h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Discover jobs, understand your match, build stronger resumes and track every application — without switching between five different tools.</p>
        <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/jobs" className="rounded-xl bg-violet-600 px-7 py-4 text-center font-bold text-white shadow-xl shadow-violet-200/60 transition hover:-translate-y-0.5 hover:bg-violet-700">Explore jobs →</Link><Link href="/resume" className="rounded-xl border border-slate-200 bg-white px-7 py-4 text-center font-bold shadow-sm transition hover:border-slate-300">Build your resume</Link></div>
        <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-slate-500"><span>✓ ATS-friendly resumes</span><span>✓ India-first job filters</span><span>✓ Free to get started</span></div>
      </div>

      <div className="relative mx-auto hidden min-h-[500px] w-full max-w-xl sm:block [perspective:1500px]"><div className="absolute inset-8 rounded-full bg-violet-200/35 blur-3xl"/>
        <div className="absolute left-3 top-14 w-[82%] rounded-[28px] border border-white bg-white/95 p-6 shadow-[0_35px_90px_rgba(15,23,42,.15)] [transform:rotateY(-8deg)_rotateX(3deg)]"><div className="flex items-start justify-between"><div><p className="text-xs font-black tracking-[.16em] text-violet-600">YOUR TOP MATCH</p><p className="mt-2 text-sm font-bold text-slate-400">Aster Analytics</p><h2 className="mt-1 text-3xl font-black tracking-tight">Data Analyst</h2><p className="mt-2 text-sm text-slate-500">Bengaluru · Hybrid · ₹5.5–8.5 LPA</p></div><div className="flex h-20 w-20 items-center justify-center rounded-full border-[8px] border-emerald-100 bg-emerald-50 text-xl font-black text-emerald-600">87%</div></div><div className="mt-6 flex flex-wrap gap-2">{["SQL ✓","Power BI ✓","Excel ✓","Python ✓"].map(x=><span key={x} className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700">{x}</span>)}</div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span className="font-bold">Strong fit</span><span className="text-slate-500">4 of 5 core skills</span></div><div className="mt-3 h-2 rounded-full bg-slate-200"><div className="h-2 w-[87%] rounded-full bg-emerald-500"/></div></div></div>
        <div className="absolute bottom-9 right-0 w-[62%] rounded-[26px] bg-[#090d1f] p-5 text-white shadow-[0_30px_70px_rgba(15,23,42,.3)] [transform:rotateY(10deg)_translateZ(70px)]"><p className="text-xs font-black tracking-[.15em] text-violet-300">APPLICATIONS</p>{[["Saved","12"],["Applied","8"],["Interview","3"],["Offer","1"]].map(([a,b],i)=><div key={a} className="mt-3 flex items-center justify-between rounded-xl bg-white/10 px-4 py-3"><span className="flex items-center gap-3 font-semibold"><i className={`h-2 w-2 rounded-full ${i===3?"bg-emerald-400":"bg-violet-400"}`}/>{a}</span><b>{b}</b></div>)}</div>
        <div className="absolute right-8 top-0 rounded-2xl border border-white bg-white px-4 py-3 shadow-xl [transform:rotate(5deg)_translateZ(100px)]"><p className="text-xs font-bold text-slate-400">Missing skill</p><p className="mt-1 font-black">Tableau</p></div>
      </div>
    </div></section>

    <section className="border-y border-slate-200/70 bg-[#fafafe]"><div className="mx-auto flex max-w-[1380px] flex-wrap items-center justify-between gap-5 px-5 py-6 text-sm sm:px-8"><span className="font-bold text-slate-400">ONE SIMPLE WORKFLOW</span>{["Discover","Match","Tailor","Track"].map((x,i)=><div key={x} className="flex items-center gap-3 font-black"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-violet-100 text-xs text-violet-700">{i+1}</span>{x}{i<3&&<span className="hidden text-slate-300 md:inline">→</span>}</div>)}</div></section>

    <section className="mx-auto max-w-[1380px] px-5 py-20 sm:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-sm font-black tracking-[.16em] text-violet-600">EVERYTHING IN ONE PLACE</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Less admin. More confident applications.</h2><p className="mt-5 text-lg leading-8 text-slate-600">A focused toolkit that helps you decide what to apply for and keeps the process moving.</p></div>
      <div className="mt-12 grid gap-4 md:grid-cols-2">{features.map(([num,title,text,icon])=><article key={num} className="group rounded-[26px] border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:border-violet-200 hover:shadow-[0_22px_60px_rgba(15,23,42,.08)]"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#090d1f] text-xl text-white">{icon}</span><span className="text-xs font-black tracking-[.15em] text-slate-300">{num}</span></div><h3 className="mt-8 text-2xl font-black tracking-tight">{title}</h3><p className="mt-3 max-w-xl leading-7 text-slate-600">{text}</p></article>)}</div>
    </section>

    <section className="mx-auto max-w-[1380px] px-5 pb-20 sm:px-8"><div className="relative overflow-hidden rounded-[30px] bg-[#090d1f] px-7 py-12 text-white sm:px-12 lg:flex lg:items-center lg:justify-between"><div className="absolute right-0 top-0 h-64 w-64 rounded-full bg-violet-600/20 blur-3xl"/><div className="relative"><p className="text-sm font-black tracking-[.15em] text-violet-300">YOUR NEXT APPLICATION STARTS HERE</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-.035em]">Build your profile once. Use it across your whole search.</h2><p className="mt-4 max-w-xl leading-7 text-slate-300">Start with the non-AI JobCraft workflow today. Smarter AI assistance will plug into the same product later.</p></div><Link href="/auth/signup" className="relative mt-8 inline-block shrink-0 rounded-xl bg-white px-7 py-4 font-black text-slate-950 transition hover:-translate-y-0.5 lg:mt-0">Create free account →</Link></div></section>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-[1380px] flex-col gap-5 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><div><b className="text-lg text-slate-950">Job<span className="text-violet-600">Craft</span></b><p className="mt-1">Career tools designed for India.</p></div><div className="flex flex-wrap gap-6 font-semibold"><Link href="/jobs">Jobs</Link><Link href="/resume">Resume</Link><Link href="/applications">Applications</Link></div></div></footer>
  </main>;
}
