import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { deleteResume, setPrimaryResume, uploadResume } from "./actions";

export default async function ResumePage({ searchParams }: { searchParams: Promise<{ error?: string; uploaded?: string }> }) {
  const params = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/login");

  const { data: resumes } = await supabase.from("resumes").select("id,name,is_primary,storage_path,created_at,structured_data").eq("user_id", user.id).order("is_primary", { ascending: false }).order("created_at", { ascending: false });
  const builtCount = resumes?.filter((resume: any) => !resume.storage_path).length ?? 0;
  const uploadedCount = resumes?.filter((resume: any) => Boolean(resume.storage_path)).length ?? 0;
  const primary = resumes?.find((resume: any) => resume.is_primary);

  return <main className="min-h-screen bg-[#f7f8fc] text-[#090d1f]">
    <header className="border-b border-slate-200/70 bg-white"><div className="mx-auto flex max-w-[1200px] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3 font-black"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#090d1f] text-sm text-white">JC</span><span className="text-xl">Job<span className="text-violet-600">Craft</span></span></Link><Link href="/dashboard" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold">← Dashboard</Link></div></header>

    <section className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8 lg:py-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-black tracking-[.14em] text-violet-600">RESUME WORKSPACE</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Keep every version organised.</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">Upload an existing resume, build an ATS-friendly JobCraft version and keep a clear primary resume for your search.</p></div><Link href="/resume/builder" className="rounded-xl bg-violet-600 px-6 py-3.5 text-center font-black text-white shadow-lg shadow-violet-200">Build a resume →</Link></div>

    {params.error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{params.error}</p>}{params.uploaded&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-800">Resume uploaded successfully.</p>}

    <div className="mt-8 grid gap-4 sm:grid-cols-3">{[["Total resumes",resumes?.length??0],["Built in JobCraft",builtCount],["Uploaded files",uploadedCount]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">{String(label)}</p><p className="mt-2 text-3xl font-black">{String(value)}</p></div>)}</div>

    <div className="mt-8 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="space-y-5"><section className="rounded-[24px] border border-slate-200 bg-white p-6"><p className="text-sm font-black">Primary resume</p>{primary?<><h2 className="mt-3 text-xl font-black">{primary.name}</h2><p className="mt-1 text-sm text-slate-500">{primary.storage_path?"Uploaded file":"Built in JobCraft"}</p><p className="mt-4 text-sm leading-6 text-slate-600">This is the resume JobCraft should treat as your default version.</p></>:<><p className="mt-3 text-sm leading-6 text-slate-600">Choose a primary resume once you add your first version.</p></>}</section>
      <section className="rounded-[24px] border border-slate-200 bg-white p-6"><p className="text-sm font-black">Upload an existing resume</p><p className="mt-2 text-sm leading-6 text-slate-500">PDF or DOCX, maximum 5 MB. Files are stored privately.</p><form action={uploadResume} className="mt-5 space-y-3"><input name="name" placeholder="Resume name e.g. Data Analyst" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 outline-none focus:border-violet-400 focus:bg-white"/><input name="file" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"/><button className="w-full rounded-xl bg-[#090d1f] px-5 py-3.5 font-black text-white">Upload resume</button></form></section></aside>

      <section><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.14em] text-violet-600">YOUR VERSIONS</p><h2 className="mt-2 text-2xl font-black">Resumes ready for your search</h2></div></div><div className="mt-5 space-y-4">{resumes?.length?resumes.map((resume:any)=><article key={resume.id} className="rounded-[22px] border border-slate-200 bg-white p-5 shadow-sm transition hover:border-violet-200"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-violet-50 font-black text-violet-700">CV</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-black">{resume.name}</h3>{resume.is_primary&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">Primary</span>}</div><p className="mt-1 text-sm text-slate-500">{resume.storage_path?"Uploaded resume":"JobCraft resume"} · Added {new Date(resume.created_at).toLocaleDateString("en-IN")}</p><p className="mt-2 text-sm text-slate-600">{resume.storage_path?"Keep this as a source document or use it as your default resume.":"Editable ATS-friendly version built inside JobCraft."}</p></div></div><div className="flex flex-wrap gap-2">{!resume.storage_path&&<Link href={`/resume/builder?id=${resume.id}`} className="rounded-xl bg-violet-50 px-4 py-2.5 text-sm font-black text-violet-700">Edit</Link>}{!resume.is_primary&&<form action={setPrimaryResume}><input type="hidden" name="id" value={resume.id}/><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Set primary</button></form>}<form action={deleteResume}><input type="hidden" name="id" value={resume.id}/><button className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-black text-red-700">Delete</button></form></div></div></article>):<div className="rounded-[22px] border border-dashed border-slate-300 bg-white p-10 text-center"><h3 className="text-xl font-black">Create your first resume</h3><p className="mt-2 text-slate-600">Build an ATS-friendly version or upload an existing file.</p><Link href="/resume/builder" className="mt-5 inline-block rounded-xl bg-violet-600 px-5 py-3 font-black text-white">Start building →</Link></div>}</div></section></div>
    </section>
  </main>;
}
