import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import PremiumPageVisual from "@/components/premium-page-visual";

function matchDetails(jobSkills:string[],userSkills:string[]){if(!userSkills.length||!jobSkills.length)return null;const n=new Set(userSkills.map(s=>s.toLowerCase()));const matched=jobSkills.filter(s=>n.has(s.toLowerCase()));const missing=jobSkills.filter(s=>!n.has(s.toLowerCase()));return{score:Math.round(matched.length/jobSkills.length*100),matched,missing}}
function initials(company:string){return company.split(" ").filter(Boolean).slice(0,2).map(w=>w[0]).join("").toUpperCase()}

export default async function JobsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const params=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();let userSkills:string[]=[];if(user){const{data:p}=await supabase.from("profiles").select("skills").eq("id",user.id).maybeSingle();userSkills=p?.skills??[]}
  let query=supabase.from("jobs").select("*").eq("is_active",true).order("posted_at",{ascending:false});if(params.q)query=query.or(`title.ilike.%${params.q}%,company.ilike.%${params.q}%,description.ilike.%${params.q}%`);if(params.location)query=query.ilike("location",`%${params.location}%`);if(params.work_mode)query=query.eq("work_mode",params.work_mode);if(params.experience)query=query.lte("experience_min",Number(params.experience));if(params.salary)query=query.gte("salary_max_lpa",Number(params.salary));if(params.skill)query=query.contains("skills",[params.skill]);const{data:jobs,error}=await query;

  return <main className="min-h-screen bg-[#f5f6fb] text-[#090d1f]">
    <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-white/82 backdrop-blur-2xl"><div className="mx-auto flex max-w-[1380px] items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3 font-black"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#090d1f] text-sm text-white shadow-lg">JC</span><span className="text-xl">Job<span className="text-violet-600">Craft</span></span></Link><nav className="hidden gap-8 text-sm font-semibold text-slate-500 md:flex"><Link href="/jobs" className="text-slate-950">Jobs</Link><Link href="/resume" className="hover:text-slate-950">Resume</Link><Link href="/applications" className="hover:text-slate-950">Applications</Link><Link href="/career-assistant" className="hover:text-slate-950">Career Assistant</Link></nav>{user?<Link href="/dashboard" className="rounded-xl bg-[#090d1f] px-5 py-3 text-sm font-bold text-white">Dashboard</Link>:<div className="flex items-center gap-3"><Link href="/jobs?auth=login" scroll={false} className="hidden text-sm font-bold sm:block">Log in</Link><Link href="/jobs?auth=signup" scroll={false} className="rounded-xl bg-[#090d1f] px-5 py-3 text-sm font-bold text-white">Get started</Link></div>}</div></header>

    <section className="relative overflow-hidden border-b border-slate-200/70 bg-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_20%,rgba(124,58,237,.12),transparent_30%),radial-gradient(circle_at_88%_15%,rgba(14,165,233,.08),transparent_28%)]"/><div className="relative mx-auto grid max-w-[1380px] gap-7 px-5 py-10 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:py-14"><div><p className="text-xs font-black tracking-[.18em] text-violet-600">INDIA-FIRST JOB DISCOVERY</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-5xl">Find roles worth your attention, not just your clicks.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Search by the things that actually change a decision, then use your profile to understand fit before you spend time applying.</p><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-full border border-violet-100 bg-violet-50 px-4 py-2 text-xs font-black text-violet-700">SALARY IN LPA</span><span className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-600">SKILLS</span><span className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-600">EXPERIENCE</span><span className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-slate-600">WORK MODE</span></div></div><PremiumPageVisual variant="jobs" compact /></div>

      <div className="relative mx-auto max-w-[1380px] px-5 pb-10 sm:px-8"><div className="rounded-2xl border border-amber-200 bg-amber-50/80 px-5 py-4 text-sm leading-6 text-amber-950 backdrop-blur"><b>MVP preview:</b> these {jobs?.length??0} roles are sample listings used to demonstrate JobCraft search and matching. They are not live employer vacancies yet.</div>
      <form className="mt-5 rounded-[26px] border border-slate-200 bg-white p-4 shadow-[0_20px_60px_rgba(15,23,42,.08)]"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{[["q","Role, skill or company"],["location","City e.g. Bengaluru"]].map(([n,p])=><input key={n} name={n} defaultValue={params[n]} placeholder={p} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5 outline-none transition focus:border-violet-400 focus:bg-white"/>)}<select name="work_mode" defaultValue={params.work_mode??""} className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5"><option value="">Any work mode</option><option>On-site</option><option>Hybrid</option><option>Remote</option></select><input name="experience" defaultValue={params.experience} type="number" min="0" placeholder="Maximum experience" className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5"/><input name="salary" defaultValue={params.salary} type="number" min="0" step="0.5" placeholder="Minimum salary (LPA)" className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5"/><input name="skill" defaultValue={params.skill} placeholder="Skill e.g. SQL" className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3.5"/></div><div className="mt-3 flex flex-wrap gap-3"><button className="rounded-xl bg-violet-600 px-6 py-3.5 font-black text-white shadow-lg shadow-violet-200 transition hover:-translate-y-0.5">Search jobs</button><Link href="/jobs" className="rounded-xl border border-slate-200 px-6 py-3.5 font-black text-slate-600">Clear</Link>{!user&&<Link href="/jobs?auth=signup" scroll={false} className="ml-auto hidden items-center text-sm font-black text-violet-600 sm:flex">Create profile for match scores →</Link>}</div></form></div>
    </section>

    <section className="mx-auto max-w-[1380px] px-5 py-9 sm:px-8">{error&&<p className="mb-4 rounded-xl bg-red-50 p-4 text-red-700">Could not load jobs: {error.message}</p>}<div className="space-y-4">{(jobs??[]).map(job=>{const match=matchDetails(job.skills??[],userSkills);const tone=match&&match.score>=70?"text-emerald-600":match&&match.score>=45?"text-amber-600":"text-slate-700";return <article key={job.id} className="group relative overflow-hidden rounded-[26px] border border-slate-200 bg-white p-5 shadow-[0_10px_35px_rgba(15,23,42,.05)] transition duration-300 hover:-translate-y-1 hover:border-violet-200 hover:shadow-[0_24px_65px_rgba(15,23,42,.10)] sm:p-6"><div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-violet-500 to-indigo-500 opacity-0 transition group-hover:opacity-100"/><div className="grid gap-6 lg:grid-cols-[1fr_240px]"><div><div className="flex gap-4"><div className="flex h-13 w-13 shrink-0 items-center justify-center rounded-2xl bg-[#090d1f] text-sm font-black text-white shadow-lg">{initials(job.company)}</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-violet-600">{job.company}</p><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-black tracking-wide text-amber-700">SAMPLE ROLE</span></div><h2 className="mt-1 text-2xl font-black tracking-tight">{job.title}</h2><div className="mt-2 flex flex-wrap gap-x-2 gap-y-1 text-sm text-slate-500"><span>{job.location}</span><span>·</span><span>{job.work_mode}</span><span>·</span><span>{job.salary_min_lpa?`₹${job.salary_min_lpa}–${job.salary_max_lpa} LPA`:"Salary not listed"}</span><span>·</span><span>{job.experience_min}–{job.experience_max??"+"} yrs</span></div></div></div><p className="mt-5 max-w-3xl leading-7 text-slate-600">{job.description}</p><div className="mt-5 flex flex-wrap gap-2">{(job.skills??[]).map((skill:string)=>{const yes=match?.matched.some(x=>x.toLowerCase()===skill.toLowerCase());return <span key={skill} className={`rounded-lg px-3 py-1.5 text-sm font-bold ${yes?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{skill}{yes?" ✓":""}</span>})}</div></div>
        <aside className="flex flex-col justify-between rounded-[20px] border border-slate-100 bg-gradient-to-br from-slate-50 to-white p-5">{match?<div><div className="flex items-end justify-between"><div><p className="text-[10px] font-black tracking-[.15em] text-slate-400">JOBCRAFT MATCH</p><p className="mt-1 font-black">{match.score>=70?"Strong fit":match.score>=45?"Potential fit":"Needs review"}</p></div><span className={`text-3xl font-black ${tone}`}>{match.score}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 to-emerald-500" style={{width:`${match.score}%`}}/></div><p className="mt-4 text-xs leading-5 text-slate-500">{match.missing.length?`Visible gap: ${match.missing.slice(0,2).join(", ")}`:"Your saved skills cover the listed core skills."}</p></div>:<div><p className="text-[10px] font-black tracking-[.15em] text-violet-600">PERSONALISE YOUR SEARCH</p><p className="mt-2 font-black">See your match score</p><p className="mt-2 text-sm leading-6 text-slate-500">{user?"Add skills to your profile to compare each role.":"Create a profile to see matched and missing skills."}</p></div>}<Link href={`/jobs/${job.id}`} className="mt-5 rounded-xl bg-[#090d1f] px-5 py-3 text-center font-black text-white transition group-hover:bg-violet-600">Preview role →</Link></aside></div></article>})}</div>{!jobs?.length&&!error&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-600">No sample roles matched your filters. Try widening your search.</div>}</section>
  </main>
}
